/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dbpan
 */
public class frmDetallePlanilla extends javax.swing.JFrame {

    private int idPlanilla;

    /**
     * Creates new form frmDetallePlanilla
     */
    public frmDetallePlanilla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPlanilla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTSBruto = new javax.swing.JLabel();
        lblTSNeto = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(138, 213, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculo_planilla.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Calculo de planilla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(734, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 70));

        jtPlanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#PLANILLA", "FECHA", "CEDULA", "NOMBRE", "APELLIDO", "HT", "SxH", "SALARIO BRUTO", "SS", "SE", "SALARIO NETO"
            }
        ));
        jtPlanilla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtPlanillaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jtPlanilla);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1000, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Total Salario Bruto: ");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Total Salario neto:");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, -1, -1));

        lblTSBruto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTSBruto.setText("xxxxxxxx");
        bg.add(lblTSBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, -1, -1));

        lblTSNeto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTSNeto.setText("xxxxxxxxx");
        lblTSNeto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblTSNetoPropertyChange(evt);
            }
        });
        bg.add(lblTSNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(138, 213, 255));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        bg.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtPlanillaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtPlanillaPropertyChange

    }//GEN-LAST:event_jtPlanillaPropertyChange

    private void lblTSNetoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblTSNetoPropertyChange

    }//GEN-LAST:event_lblTSNetoPropertyChange

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    public void setIdPlanilla(int idPlanilla) {

        this.idPlanilla = idPlanilla;
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        cargarDetallePlanilla(); // Cargar los detalles de la planilla al abrir el formulario
    }

    public void cargarDetallePlanilla() {
        DefaultTableModel modelo = (DefaultTableModel) jtPlanilla.getModel();

        // Luego, limpiamos cualquier contenido que pueda haber en la tabla actualmente
        modelo.setRowCount(0);
        DefaultTableModel modeloDetalle = (DefaultTableModel) jtPlanilla.getModel();
        modeloDetalle.setRowCount(0); // Limpiar el contenido actual de la tabla jtPlanilla

        MostrarDetallePlanilla obj_detalle_planilla = new MostrarDetallePlanilla();

        ArrayList<MostrarDetallePlanilla> lista_detalle = obj_detalle_planilla.mostrar_detalle_planillas(this.idPlanilla);

        for (MostrarDetallePlanilla detalle : lista_detalle) {
            String[] arregloDetalle = {
                String.valueOf(detalle.getId_detalle_planilla()),
                String.valueOf(detalle.getFecha_creacion()),
                detalle.getCedula_empleado(),
                detalle.getNombre_empleado(),
                detalle.getApellido_empleado(),
                String.valueOf(detalle.getHoras_trabajadas()),
                String.valueOf(detalle.getSalario_por_hora()),
                String.valueOf(detalle.getSalario_bruto()),
                String.valueOf(detalle.getSeguro_social()),
                String.valueOf(detalle.getSeguro_educativo()),
                String.valueOf(detalle.getSalario_neto()),
                String.valueOf(detalle.getTotal_salario_bruto()),
                String.valueOf(detalle.getTotal_salario_neto())
            };
            modeloDetalle.addRow(arregloDetalle);

        }
        double totalSalarioNeto = calcularSumaSalarioNeto(modelo);
        lblTSNeto.setText(String.valueOf(totalSalarioNeto));
        double totalSalarioBruto = calcularSumaSalarioBruto(modelo);
        lblTSBruto.setText(String.valueOf(totalSalarioBruto));
    }

    private double calcularSumaSalarioNeto(DefaultTableModel modelo) {
        double totalSalarioNeto = 0.0;
        int columnaSalarioNeto = 10; // Número de columna correspondiente a "Salario Neto"

        for (int i = 0; i < modelo.getRowCount(); i++) {
            double salarioNeto = Double.parseDouble(modelo.getValueAt(i, columnaSalarioNeto).toString());
            totalSalarioNeto += salarioNeto;
        }

        return totalSalarioNeto;
    }

    private double calcularSumaSalarioBruto(DefaultTableModel modelo) {
        double totalSalarioBruto = 0.0;
        int columnaSalarioBruto = 7; // Número de columna correspondiente a "Salario Bruto"

        for (int i = 0; i < modelo.getRowCount(); i++) {
            double salarioBruto = Double.parseDouble(modelo.getValueAt(i, columnaSalarioBruto).toString());
            totalSalarioBruto += salarioBruto;
        }

        return totalSalarioBruto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDetallePlanilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDetallePlanilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPlanilla;
    private javax.swing.JLabel lblTSBruto;
    private javax.swing.JLabel lblTSNeto;
    // End of variables declaration//GEN-END:variables
}
